# Generated by Django 4.2.7 on 2026-06-24 18:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the weather record')),
                ('city', models.CharField(choices=[('Lahore', 'Lahore'), ('Karachi', 'Karachi'), ('Islamabad', 'Islamabad'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Sialkot', 'Sialkot'), ('Gujranwala', 'Gujranwala'), ('Hyderabad', 'Hyderabad'), ('Bahawalpur', 'Bahawalpur')], max_length=100)),
                ('temperature_max', models.FloatField(validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('temperature_min', models.FloatField(validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('temperature_avg', models.FloatField(validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('humidity', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('precipitation', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wind_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('wind_direction', models.CharField(max_length=20)),
                ('pressure', models.FloatField(validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(1200)])),
                ('visibility', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('weather_condition', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-date', 'city'],
                'indexes': [models.Index(fields=['date'], name='weather_wea_date_6c0bdb_idx'), models.Index(fields=['city'], name='weather_wea_city_226bd6_idx'), models.Index(fields=['date', 'city'], name='weather_wea_date_c00ad5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('cities_included', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('user', 'report_date')},
            },
        ),
    ]
